In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
switz=pd.read_csv('D:/Technocolabs Final work files/k=5_MergedData/Switzerland.csv')

In [4]:
switz.head()

Year       PPP  Exchange           GDP  vector_1  vector_2  vector_3  \
0  1981  1.892582  1.964242  1.090000e+11  0.100003  0.100004  0.100066   
1  1982  1.913434  2.030275  1.120000e+11  0.200000  0.200000  0.200000   
2  1983  1.884895  2.099142  1.110000e+11  0.092599  0.552755  0.166161   
3  1984  1.887659  2.349683  1.060000e+11  0.100043  0.599702  0.100172   
4  1985  1.871343  2.457125  1.080000e+11  0.082920  0.350074  0.399832   

   vector_4  vector_5  
0  0.100020  0.599906  
1  0.200000  0.200000  
2  0.095321  0.093163  
3  0.100015  0.100069  
4  0.083997  0.083177

In [5]:
X=switz.drop('Exchange',axis=1)
X

Year       PPP           GDP  vector_1  vector_2  vector_3  vector_4  \
0   1981  1.892582  1.090000e+11  0.100003  0.100004  0.100066  0.100020   
1   1982  1.913434  1.120000e+11  0.200000  0.200000  0.200000  0.200000   
2   1983  1.884895  1.110000e+11  0.092599  0.552755  0.166161  0.095321   
3   1984  1.887659  1.060000e+11  0.100043  0.599702  0.100172  0.100015   
4   1985  1.871343  1.080000e+11  0.082920  0.350074  0.399832  0.083997   
5   1986  1.890066  1.540000e+11  0.100043  0.599706  0.100168  0.100014   
6   1987  1.884920  1.930000e+11  0.200000  0.200000  0.200000  0.200000   
7   1988  1.871498  2.090000e+11  0.100043  0.599704  0.100169  0.100014   
8   1989  1.863180  2.020000e+11  0.267549  0.082896  0.482542  0.083702   
9   1990  1.936289  2.580000e+11  0.200000  0.200000  0.200000  0.200000   
10  1991  1.974260  2.610000e+11  0.200000  0.200000  0.200000  0.200000   
11  1992  1.971282  2.720000e+11  0.100003  0.100004  0.100066  0.100020   
12  1993  1.970372  2.640000e+11  0.077464  0.073236  0.230987  0.077500   
13  1994  1.952026  2.930000e+11  0.599077  0.100005  0.100662  0.100023   
14  1995  1.926041  3.430000e+11  0.088975  0.085419  0.085452  0.087372   
15  1996  1.891189  3.300000e+11  0.151969  0.153923  0.074708  0.074724   
16  1997  1.844334  2.870000e+11  0.666820  0.082881  0.083114  0.083779   
17  1998  1.827663  2.950000e+11  0.200000  0.200000  0.200000  0.200000   
18  1999  1.802836  2.900000e+11  0.100004  0.100023  0.598393  0.101306   
19  2000  1.788109  2.720000e+11  0.079377  0.207023  0.076489  0.077989   
20  2001  1.768379  2.790000e+11  0.100003  0.100004  0.100066  0.100020   
21  2002  1.709760  3.010000e+11  0.093425  0.080196  0.102873  0.082508   
22  2003  1.717018  3.530000e+11  0.082981  0.076759  0.098497  0.079952   
23  2004  1.693209  3.940000e+11  0.082920  0.358420  0.083097  0.082907   
24  2005  1.686548  4.090000e+11  0.100004  0.100023  0.598410  0.101290   
25  2006  1.600989  4.310000e+11  0.200000  0.200000  0.200000  0.200000   
26  2007  1.533994  4.800000e+11  0.100043  0.599705  0.100169  0.100014   
27  2008  1.493049  5.540000e+11  0.599080  0.100005  0.100659  0.100023   
28  2009  1.468980  5.420000e+11  0.666814  0.082881  0.083114  0.083784   
29  2010  1.464944  5.840000e+11  0.666819  0.082881  0.083114  0.083779   
30  2011  1.397498  7.000000e+11  0.100004  0.100023  0.598416  0.101283   
31  2012  1.354072  6.680000e+11  0.100004  0.100023  0.598395  0.101305   
32  2013  1.312477  6.890000e+11  0.599083  0.100005  0.100655  0.100023   
33  2014  1.281761  7.090000e+11  0.200000  0.200000  0.200000  0.200000   
34  2015  1.235788  6.800000e+11  0.596414  0.100008  0.100008  0.102422   
35  2016  1.201964  6.710000e+11  0.200000  0.200000  0.200000  0.200000   
36  2017  1.187726  6.800000e+11  0.100043  0.599705  0.100169  0.100014   
37  2018  1.178680  7.050000e+11  0.506295  0.272260  0.073604  0.074063   

    vector_5  
0   0.599906  
1   0.200000  
2   0.093163  
3   0.100069  
4   0.083177  
5   0.100069  
6   0.200000  
7   0.100069  
8   0.083311  
9   0.200000  
10  0.200000  
11  0.599907  
12  0.540812  
13  0.100233  
14  0.652782  
15  0.544675  
16  0.083406  
17  0.200000  
18  0.100275  
19  0.559122  
20  0.599907  
21  0.640998  
22  0.661811  
23  0.392656  
24  0.100275  
25  0.200000  
26  0.100069  
27  0.100233  
28  0.083406  
29  0.083406  
30  0.100274  
31  0.100275  
32  0.100233  
33  0.200000  
34  0.101148  
35  0.200000  
36  0.100069  
37  0.073779

In [6]:
y=switz['Exchange']
y

0     1.964242
1     2.030275
2     2.099142
3     2.349683
4     2.457125
5     1.798917
6     1.491192
7     1.463300
8     1.635925
9     1.389158
10    1.433992
11    1.406218
12    1.477617
13    1.367692
14    1.182469
15    1.236010
16    1.451313
17    1.449813
18    1.502155
19    1.688843
20    1.687615
21    1.558608
22    1.346651
23    1.243496
24    1.245177
25    1.253843
26    1.200366
27    1.083090
28    1.088142
29    1.042906
30    0.888042
31    0.937684
32    0.926904
33    0.916151
34    0.962381
35    0.985394
36    0.984692
37    0.977883
Name: Exchange, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression
lswzmodel=LinearRegression()
lswzmodel.fit(X_train,y_train)

LinearRegression()

In [9]:
y_pred=lswzmodel.predict(X_test)
y_pred

array([1.40912326, 0.99550452, 1.45765248, 1.26755663, 1.34457118,
       1.56597434, 1.24335605, 1.31962885])

In [10]:
from sklearn.metrics import mean_squared_error
lswzmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(lswzmodel_rmse)

0.07133450370969623


In [11]:
from sklearn import metrics
print(metrics.mean_absolute_error(y_test,y_pred))

0.061050127316752106


In [12]:
# Calculate the absolute errors
errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.06 degrees.


In [13]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 95.58 %.


### Random Forest

In [14]:
from sklearn.ensemble import RandomForestRegressor
rfswzmodel=RandomForestRegressor(n_estimators = 1000, random_state = 42)
rfswzmodel.fit(X_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [15]:
y_pred_rf=rfswzmodel.predict(X_test)
y_pred_rf

array([1.28490085, 1.0592265 , 1.56326572, 1.32263259, 1.48906821,
       1.54770358, 1.15964919, 1.42707346])

In [16]:
from sklearn.metrics import mean_squared_error
rfswzmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(rfswzmodel_rmse)

0.07133450370969623


In [17]:
rfswzmodel.feature_importances_

array([0.31984883, 0.07264946, 0.57491178, 0.00513476, 0.00747254,
       0.00872946, 0.00631973, 0.00493344])

In [18]:
# Calculate the absolute errors
errors_rf = abs(y_pred_rf - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.06 degrees.


In [19]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_rf / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 95.13 %.


### Ridge Regression

In [20]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.01)
ridge.fit(X_train, y_train) 

C:\Users\RADHIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=7.05702e-27): result may not be accurate.
  overwrite_a=True).T


Ridge(alpha=0.01)

In [21]:
from sklearn.metrics import r2_score
pred_train_rr= ridge.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train_rr)))
print(r2_score(y_train, pred_train_rr))

pred_test_rr= ridge.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred_test_rr))) 
print(r2_score(y_test, pred_test_rr))

0.12277766868124705
0.9183256294922287
0.06803640088670614
0.859814893917363


In [22]:
# Calculate the absolute errors
errors_ridge = abs(pred_test_rr - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.06 degrees.


In [23]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_ridge / pred_test_rr)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Accuracy: 95.56 %.


In [24]:
import pickle
pickle.dump(lswzmodel,open('lr_swz_model.pkl','wb'))