In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
india=pd.read_csv('D:/Technocolabs Final work files/k=5_MergedData/India.csv')

In [3]:
india.head()

Year       PPP   Exchange           GDP  vector_1  vector_2  vector_3  \
0  1981  3.379142   8.658523  1.930000e+11  0.100003  0.100004  0.100066   
1  1982  3.429847   9.455132  2.010000e+11  0.200000  0.200000  0.200000   
2  1983  3.596462  10.098898  2.180000e+11  0.092599  0.552755  0.166161   
3  1984  3.732936  11.362583  2.120000e+11  0.100043  0.599702  0.100172   
4  1985  3.857350  12.368750  2.330000e+11  0.082920  0.350074  0.399832   

   vector_4  vector_5  
0  0.100020  0.599906  
1  0.200000  0.200000  
2  0.095321  0.093163  
3  0.100015  0.100069  
4  0.083997  0.083177

In [4]:
X=india.drop('Exchange',axis=1)
X

Year        PPP           GDP  vector_1  vector_2  vector_3  vector_4  \
0   1981   3.379142  1.930000e+11  0.100003  0.100004  0.100066  0.100020   
1   1982   3.429847  2.010000e+11  0.200000  0.200000  0.200000  0.200000   
2   1983   3.596462  2.180000e+11  0.092599  0.552755  0.166161  0.095321   
3   1984   3.732936  2.120000e+11  0.100043  0.599702  0.100172  0.100015   
4   1985   3.857350  2.330000e+11  0.082920  0.350074  0.399832  0.083997   
5   1986   4.421835  2.490000e+11  0.100043  0.599706  0.100168  0.100014   
6   1987   4.717656  2.790000e+11  0.200000  0.200000  0.200000  0.200000   
7   1988   4.932062  2.970000e+11  0.100043  0.599704  0.100169  0.100014   
8   1989   5.146414  2.960000e+11  0.267549  0.082896  0.482542  0.083702   
9   1990   5.489942  3.210000e+11  0.200000  0.200000  0.200000  0.200000   
10  1991   6.040629  2.700000e+11  0.200000  0.200000  0.200000  0.200000   
11  1992   6.435521  2.880000e+11  0.100003  0.100004  0.100066  0.100020   
12  1993   6.906543  2.790000e+11  0.077464  0.073236  0.230987  0.077500   
13  1994   7.437011  3.270000e+11  0.599077  0.100005  0.100662  0.100023   
14  1995   7.944424  3.600000e+11  0.088975  0.085419  0.085452  0.087372   
15  1996   8.392545  3.930000e+11  0.151969  0.153923  0.074708  0.074724   
16  1997   8.784588  4.160000e+11  0.666820  0.082881  0.083114  0.083779   
17  1998   9.382645  4.210000e+11  0.200000  0.200000  0.200000  0.200000   
18  1999   9.532905  4.590000e+11  0.100004  0.100023  0.598393  0.101306   
19  2000   9.664333  4.680000e+11  0.079377  0.207023  0.076489  0.077989   
20  2001   9.761001  4.850000e+11  0.100003  0.100004  0.100066  0.100020   
21  2002   9.966049  5.150000e+11  0.093425  0.080196  0.102873  0.082508   
22  2003  10.162784  6.080000e+11  0.082981  0.076759  0.098497  0.079952   
23  2004  10.462960  7.090000e+11  0.082920  0.358420  0.083097  0.082907   
24  2005  10.717338  8.200000e+11  0.100004  0.100023  0.598410  0.101290   
25  2006  11.276447  9.400000e+11  0.200000  0.200000  0.200000  0.200000   
26  2007  11.744053  1.220000e+12  0.100043  0.599705  0.100169  0.100014   
27  2008  12.579117  1.200000e+12  0.599080  0.100005  0.100659  0.100023   
28  2009  13.362861  1.340000e+12  0.666814  0.082881  0.083114  0.083784   
29  2010  14.599321  1.680000e+12  0.666819  0.082881  0.083114  0.083779   
30  2011  15.549549  1.820000e+12  0.100004  0.100023  0.598416  0.101283   
31  2012  16.160835  1.830000e+12  0.100004  0.100023  0.598395  0.101305   
32  2013  17.342325  1.860000e+12  0.599083  0.100005  0.100655  0.100023   
33  2014  18.386549  2.040000e+12  0.200000  0.200000  0.200000  0.200000   
34  2015  19.235003  2.100000e+12  0.596414  0.100008  0.100008  0.102422   
35  2016  19.898727  2.290000e+12  0.200000  0.200000  0.200000  0.200000   
36  2017  20.647793  2.650000e+12  0.100043  0.599705  0.100169  0.100014   
37  2018  21.075024  2.710000e+12  0.506295  0.272260  0.073604  0.074063   

    vector_5  
0   0.599906  
1   0.200000  
2   0.093163  
3   0.100069  
4   0.083177  
5   0.100069  
6   0.200000  
7   0.100069  
8   0.083311  
9   0.200000  
10  0.200000  
11  0.599907  
12  0.540812  
13  0.100233  
14  0.652782  
15  0.544675  
16  0.083406  
17  0.200000  
18  0.100275  
19  0.559122  
20  0.599907  
21  0.640998  
22  0.661811  
23  0.392656  
24  0.100275  
25  0.200000  
26  0.100069  
27  0.100233  
28  0.083406  
29  0.083406  
30  0.100274  
31  0.100275  
32  0.100233  
33  0.200000  
34  0.101148  
35  0.200000  
36  0.100069  
37  0.073779

In [5]:
y=india['Exchange']
y

0      8.658523
1      9.455132
2     10.098898
3     11.362583
4     12.368750
5     12.610833
6     12.961500
7     13.917083
8     16.225500
9     17.503500
10    22.742433
11    25.918083
12    30.493292
13    31.373742
14    32.427077
15    35.433173
16    36.313286
17    41.259365
18    43.055428
19    44.941605
20    47.186414
21    48.610319
22    46.583284
23    45.316467
24    44.099975
25    45.307008
26    41.348533
27    43.505183
28    48.405267
29    45.725812
30    46.670467
31    53.437233
32    58.597845
33    61.029514
34    64.151944
35    67.195313
36    65.121569
37    68.389467
Name: Exchange, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

### Linear Regression

In [8]:
from sklearn.linear_model import LinearRegression
lindmodel=LinearRegression()
lindmodel.fit(X_train,y_train)

LinearRegression()

In [9]:
y_pred=lindmodel.predict(X_test)
y_pred

array([45.48350996, 47.0671203 , 37.36230146, 37.60459523, 27.31711389,
       44.94261817, 41.73618635, 23.23996756])

In [10]:
from sklearn.metrics import mean_squared_error
lindmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(lindmodel_rmse)

1.4236326764994942


In [13]:
# print the coefficients
print(lindmodel.intercept_)
print(lindmodel.coef_)

-645.0348795245156
[ 3.21234166e-01  5.73435473e+00 -2.20055085e-11 -5.53622658e-01
  3.11399571e+00  1.72312900e-01 -6.50873049e+00  3.77604334e+00]


In [18]:
from sklearn import metrics
print(metrics.mean_absolute_error(y_test,y_pred))

1.2736917163562498


### Random Forest

In [26]:
from sklearn.ensemble import RandomForestRegressor
rfindmodel=RandomForestRegressor(n_estimators = 1000, random_state = 42)
rfindmodel.fit(X_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [27]:
y_pred=rfindmodel.predict(X_test)
y_pred

array([46.84479245, 49.06025706, 43.52121825, 34.34787025, 25.54121765,
       44.47741757, 44.83606604, 17.88283863])

In [24]:
from sklearn.metrics import mean_squared_error
rfindmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(rfindmodel_rmse)

3.432802267650464


In [25]:
rfindmodel.feature_importances_

array([0.33520363, 0.34870075, 0.30279185, 0.00251372, 0.0044593 ,
       0.00165151, 0.00193951, 0.00273974])

In [28]:
# Calculate the absolute errors
errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 2.92 degrees.


In [29]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Accuracy: 91.53 %.


In [30]:
import pickle
pickle.dump(rfindmodel,open('rf_ind_model.pkl','wb'))

### Ridge