In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
china=pd.read_csv('D:/Technocolabs Final work files/k=5_MergedData/China.csv')

In [3]:
china.head()

Year       PPP  Exchange           GDP  vector_1  vector_2  vector_3  \
0  1981  1.408056  1.704542  1.960000e+11  0.100003  0.100004  0.100066   
1  1982  1.324266  1.892542  2.050000e+11  0.200000  0.200000  0.200000   
2  1983  1.289093  1.975675  2.310000e+11  0.092599  0.552755  0.166161   
3  1984  1.305713  2.320042  2.600000e+11  0.100043  0.599702  0.100172   
4  1985  1.394914  2.936658  3.090000e+11  0.082920  0.350074  0.399832   

   vector_4  vector_5  
0  0.100020  0.599906  
1  0.200000  0.200000  
2  0.095321  0.093163  
3  0.100015  0.100069  
4  0.083997  0.083177

In [4]:
X=china.drop('Exchange',axis=1)
X

Year       PPP           GDP  vector_1  vector_2  vector_3  vector_4  \
0   1981  1.408056  1.960000e+11  0.100003  0.100004  0.100066  0.100020   
1   1982  1.324266  2.050000e+11  0.200000  0.200000  0.200000  0.200000   
2   1983  1.289093  2.310000e+11  0.092599  0.552755  0.166161  0.095321   
3   1984  1.305713  2.600000e+11  0.100043  0.599702  0.100172  0.100015   
4   1985  1.394914  3.090000e+11  0.082920  0.350074  0.399832  0.083997   
5   1986  1.431230  3.010000e+11  0.100043  0.599706  0.100168  0.100014   
6   1987  1.467670  2.730000e+11  0.200000  0.200000  0.200000  0.200000   
7   1988  1.589320  3.120000e+11  0.100043  0.599704  0.100169  0.100014   
8   1989  1.660909  3.480000e+11  0.267549  0.082896  0.482542  0.083702   
9   1990  1.692148  3.610000e+11  0.200000  0.200000  0.200000  0.200000   
10  1991  1.746699  3.830000e+11  0.200000  0.200000  0.200000  0.200000   
11  1992  1.847653  4.270000e+11  0.100003  0.100004  0.100066  0.100020   
12  1993  2.078978  4.450000e+11  0.077464  0.073236  0.230987  0.077500   
13  1994  2.455173  5.640000e+11  0.599077  0.100005  0.100662  0.100023   
14  1995  2.733376  7.350000e+11  0.088975  0.085419  0.085452  0.087372   
15  1996  2.858882  8.640000e+11  0.151969  0.153923  0.074708  0.074724   
16  1997  2.855852  9.620000e+11  0.666820  0.082881  0.083114  0.083779   
17  1998  2.798643  1.030000e+12  0.200000  0.200000  0.200000  0.200000   
18  1999  2.723965  1.090000e+12  0.100004  0.100023  0.598393  0.101306   
19  2000  2.719364  1.210000e+12  0.079377  0.207023  0.076489  0.077989   
20  2001  2.715469  1.340000e+12  0.100003  0.100004  0.100066  0.100020   
21  2002  2.689281  1.470000e+12  0.093425  0.080196  0.102873  0.082508   
22  2003  2.708980  1.660000e+12  0.082981  0.076759  0.098497  0.079952   
23  2004  2.821351  1.960000e+12  0.082920  0.358420  0.083097  0.082907   
24  2005  2.842933  2.290000e+12  0.100004  0.100023  0.598410  0.101290   
25  2006  2.867778  2.750000e+12  0.200000  0.200000  0.200000  0.200000   
26  2007  3.009186  3.550000e+12  0.100043  0.599705  0.100169  0.100014   
27  2008  3.181871  4.590000e+12  0.599080  0.100005  0.100659  0.100023   
28  2009  3.151181  5.100000e+12  0.666814  0.082881  0.083114  0.083784   
29  2010  3.329232  6.090000e+12  0.666819  0.082881  0.083114  0.083779   
30  2011  3.524468  7.550000e+12  0.100004  0.100023  0.598416  0.101283   
31  2012  3.560968  8.530000e+12  0.100004  0.100023  0.598395  0.101305   
32  2013  3.663645  9.570000e+12  0.599083  0.100005  0.100655  0.100023   
33  2014  3.758850  1.050000e+13  0.200000  0.200000  0.200000  0.200000   
34  2015  3.870697  1.110000e+13  0.596414  0.100008  0.100008  0.102422   
35  2016  3.988837  1.120000e+13  0.200000  0.200000  0.200000  0.200000   
36  2017  4.183811  1.230000e+13  0.100043  0.599705  0.100169  0.100014   
37  2018  4.227258  1.390000e+13  0.506295  0.272260  0.073604  0.074063   

    vector_5  
0   0.599906  
1   0.200000  
2   0.093163  
3   0.100069  
4   0.083177  
5   0.100069  
6   0.200000  
7   0.100069  
8   0.083311  
9   0.200000  
10  0.200000  
11  0.599907  
12  0.540812  
13  0.100233  
14  0.652782  
15  0.544675  
16  0.083406  
17  0.200000  
18  0.100275  
19  0.559122  
20  0.599907  
21  0.640998  
22  0.661811  
23  0.392656  
24  0.100275  
25  0.200000  
26  0.100069  
27  0.100233  
28  0.083406  
29  0.083406  
30  0.100274  
31  0.100275  
32  0.100233  
33  0.200000  
34  0.101148  
35  0.200000  
36  0.100069  
37  0.073779

In [10]:
y=china['Exchange']
y

0     1.704542
1     1.892542
2     1.975675
3     2.320042
4     2.936658
5     3.452792
6     3.722100
7     3.722100
8     3.765108
9     4.783208
10    5.323392
11    5.514592
12    5.761958
13    8.618743
14    8.351417
15    8.314175
16    8.289817
17    8.278958
18    8.278250
19    8.278504
20    8.277068
21    8.276957
22    8.277037
23    8.276801
24    8.194317
25    7.973438
26    7.607532
27    6.948655
28    6.831416
29    6.770269
30    6.461461
31    6.312333
32    6.195758
33    6.143434
34    6.227489
35    6.644478
36    6.758755
37    6.615957
Name: Exchange, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

### Linear Regression

In [12]:
from sklearn.linear_model import LinearRegression
lchnmodel=LinearRegression()
lchnmodel.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred=lchnmodel.predict(X_test)
y_pred

array([7.76397238, 7.53774599, 9.05121657, 8.91597439, 4.61229381,
       8.02858284, 8.24000093, 4.40652115])

In [14]:
from sklearn.metrics import mean_squared_error
lchnmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(lchnmodel_rmse)

0.6991693717867463


In [15]:
from sklearn import metrics
print(metrics.mean_absolute_error(y_test,y_pred))

0.6679828544376452


In [16]:
# Calculate the absolute errors
errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.67 degrees.


In [17]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 90.14 %.


### Random Forest

In [18]:
from sklearn.ensemble import RandomForestRegressor
rfchnmodel=RandomForestRegressor(n_estimators = 1000, random_state = 42)
rfchnmodel.fit(X_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [23]:
y_pred_rf=rfchnmodel.predict(X_test)
y_pred_rf

array([8.02446181, 6.74832256, 8.24570596, 7.90624515, 5.71259611,
       8.22998091, 7.76843605, 4.58454829])

In [20]:
from sklearn.metrics import mean_squared_error
rfchnmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(rfchnmodel_rmse)

0.32515970894842194


In [21]:
rfchnmodel.feature_importances_

array([0.30381059, 0.31472197, 0.34906254, 0.00679984, 0.00731613,
       0.00448945, 0.00782436, 0.00597512])

In [24]:
# Calculate the absolute errors
errors_rf = abs(y_pred_rf - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.67 degrees.


In [25]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_rf / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Accuracy: 96.38 %.


### Ridge Regression

In [38]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.01)
ridge.fit(X_train, y_train) 

C:\Users\RADHIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=1.69673e-29): result may not be accurate.
  overwrite_a=True).T


Ridge(alpha=0.01)

In [40]:
from sklearn.metrics import r2_score
pred_train_rr= ridge.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train_rr)))
print(r2_score(y_train, pred_train_rr))

pred_test_rr= ridge.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred_test_rr))) 
print(r2_score(y_test, pred_test_rr))

0.4707328070854407
0.9549766034864884
0.6865018218915929
0.6689056011132031


In [42]:
# Calculate the absolute errors
errors_ridge = abs(pred_test_rr - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.67 degrees.


In [43]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_ridge / pred_test_rr)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Accuracy: 89.81 %.


In [44]:
import pickle
pickle.dump(rfchnmodel,open('rf_chn_model.pkl','wb'))