In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
japan=pd.read_csv('D:/Technocolabs Final work files/k=5_MergedData/Japan.csv')

In [3]:
japan.head()

Year         PPP    Exchange           GDP  vector_1  vector_2  vector_3  \
0  1981  228.831006  220.535833  1.220000e+12  0.100003  0.100004  0.100066   
1  1982  219.276639  249.076667  1.130000e+12  0.200000  0.200000  0.200000   
2  1983  213.007241  237.511667  1.240000e+12  0.092599  0.552755  0.166161   
3  1984  208.619258  237.522500  1.320000e+12  0.100043  0.599702  0.100172   
4  1985  204.772357  238.535833  1.400000e+12  0.082920  0.350074  0.399832   

   vector_4  vector_5  
0  0.100020  0.599906  
1  0.200000  0.200000  
2  0.095321  0.093163  
3  0.100015  0.100069  
4  0.083997  0.083177

In [4]:
X=japan.drop('Exchange',axis=1)
X

Year         PPP           GDP  vector_1  vector_2  vector_3  vector_4  \
0   1981  228.831006  1.220000e+12  0.100003  0.100004  0.100066  0.100020   
1   1982  219.276639  1.130000e+12  0.200000  0.200000  0.200000  0.200000   
2   1983  213.007241  1.240000e+12  0.092599  0.552755  0.166161  0.095321   
3   1984  208.619258  1.320000e+12  0.100043  0.599702  0.100172  0.100015   
4   1985  204.772357  1.400000e+12  0.082920  0.350074  0.399832  0.083997   
5   1986  203.966037  2.080000e+12  0.100043  0.599706  0.100168  0.100014   
6   1987  198.730394  2.530000e+12  0.200000  0.200000  0.200000  0.200000   
7   1988  193.159463  3.070000e+12  0.100043  0.599704  0.100169  0.100014   
8   1989  189.792476  3.050000e+12  0.267549  0.082896  0.482542  0.083702   
9   1990  187.710514  3.130000e+12  0.200000  0.200000  0.200000  0.200000   
10  1991  186.886354  3.580000e+12  0.200000  0.200000  0.200000  0.200000   
11  1992  185.767602  3.910000e+12  0.100003  0.100004  0.100066  0.100020   
12  1993  182.499528  4.450000e+12  0.077464  0.073236  0.230987  0.077500   
13  1994  179.158384  4.910000e+12  0.599077  0.100005  0.100662  0.100023   
14  1995  174.542779  5.450000e+12  0.088975  0.085419  0.085452  0.087372   
15  1996  170.553311  4.830000e+12  0.151969  0.153923  0.074708  0.074724   
16  1997  168.506941  4.410000e+12  0.666820  0.082881  0.083114  0.083779   
17  1998  166.556261  4.030000e+12  0.200000  0.200000  0.200000  0.200000   
18  1999  162.035740  4.560000e+12  0.100004  0.100023  0.598393  0.101306   
19  2000  154.717851  4.890000e+12  0.079377  0.207023  0.076489  0.077989   
20  2001  149.724877  4.300000e+12  0.100003  0.100004  0.100066  0.100020   
21  2002  143.774205  4.120000e+12  0.093425  0.080196  0.102873  0.082508   
22  2003  139.516091  4.450000e+12  0.082981  0.076759  0.098497  0.079952   
23  2004  134.363066  4.820000e+12  0.082920  0.358420  0.083097  0.082907   
24  2005  129.551955  4.760000e+12  0.100004  0.100023  0.598410  0.101290   
25  2006  124.536829  4.530000e+12  0.200000  0.200000  0.200000  0.200000   
26  2007  120.394201  4.520000e+12  0.100043  0.599705  0.100169  0.100014   
27  2008  116.845814  5.040000e+12  0.599080  0.100005  0.100659  0.100023   
28  2009  115.150066  5.230000e+12  0.666814  0.082881  0.083114  0.083784   
29  2010  111.666587  5.700000e+12  0.666819  0.082881  0.083114  0.083779   
30  2011  107.454281  6.160000e+12  0.100004  0.100023  0.598416  0.101283   
31  2012  104.273972  6.200000e+12  0.100004  0.100023  0.598395  0.101305   
32  2013  101.302673  5.160000e+12  0.599083  0.100005  0.100655  0.100023   
33  2014  103.052076  4.850000e+12  0.200000  0.200000  0.200000  0.200000   
34  2015  103.469437  4.390000e+12  0.596414  0.100008  0.100008  0.102422   
35  2016  105.519502  4.920000e+12  0.200000  0.200000  0.200000  0.200000   
36  2017  105.101901  4.870000e+12  0.100043  0.599705  0.100169  0.100014   
37  2018  103.706485  4.950000e+12  0.506295  0.272260  0.073604  0.074063   

    vector_5  
0   0.599906  
1   0.200000  
2   0.093163  
3   0.100069  
4   0.083177  
5   0.100069  
6   0.200000  
7   0.100069  
8   0.083311  
9   0.200000  
10  0.200000  
11  0.599907  
12  0.540812  
13  0.100233  
14  0.652782  
15  0.544675  
16  0.083406  
17  0.200000  
18  0.100275  
19  0.559122  
20  0.599907  
21  0.640998  
22  0.661811  
23  0.392656  
24  0.100275  
25  0.200000  
26  0.100069  
27  0.100233  
28  0.083406  
29  0.083406  
30  0.100274  
31  0.100275  
32  0.100233  
33  0.200000  
34  0.101148  
35  0.200000  
36  0.100069  
37  0.073779

In [5]:
y=japan['Exchange']
y

0     220.535833
1     249.076667
2     237.511667
3     237.522500
4     238.535833
5     168.519833
6     144.637500
7     128.151667
8     137.964417
9     144.792500
10    134.706667
11    126.651333
12    111.197786
13    102.207806
14     94.059579
15    108.779057
16    120.990863
17    130.905301
18    113.906805
19    107.765498
20    121.528948
21    125.388019
22    115.933464
23    108.192569
24    110.218212
25    116.299312
26    117.753529
27    103.359494
28     93.570089
29     87.779875
30     79.807020
31     79.790455
32     97.595658
33    105.944781
34    121.044026
35    108.792900
36    112.166141
37    110.423179
Name: Exchange, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

### Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression
ljpnmodel=LinearRegression()
ljpnmodel.fit(X_train,y_train)

LinearRegression()

In [8]:
y_pred=ljpnmodel.predict(X_test)
y_pred

array([125.05607543,  74.93763642, 111.86635958, 101.85160486,
       133.25379525, 126.91832342, 116.30400639, 135.75515335])

In [9]:
from sklearn.metrics import mean_squared_error
ljpnmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(ljpnmodel_rmse)

7.54345400827422


In [10]:
from sklearn import metrics
print(metrics.mean_absolute_error(y_test,y_pred))

6.56333148696849


In [11]:
# Calculate the absolute errors
errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 6.56 degrees.


In [12]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 93.99 %.


### Random Forest

In [13]:
from sklearn.ensemble import RandomForestRegressor
rfjpnmodel=RandomForestRegressor(n_estimators = 1000, random_state = 42)
rfjpnmodel.fit(X_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [14]:
y_pred_rf=rfjpnmodel.predict(X_test)
y_pred_rf

array([114.47109067,  92.41150786, 117.29303263, 108.66916012,
       132.55818845, 119.1895008 , 114.15612587, 140.31988167])

In [15]:
from sklearn.metrics import mean_squared_error
rfjpnmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(rfjpnmodel_rmse)

7.54345400827422


In [16]:
rfjpnmodel.feature_importances_

array([0.21465631, 0.3923504 , 0.37258148, 0.00343931, 0.00691093,
       0.00570702, 0.00222149, 0.00213305])

In [17]:
# Calculate the absolute errors
errors_rf = abs(y_pred_rf - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 6.56 degrees.


In [18]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_rf / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 97.06 %.


### Ridge Regression

In [19]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.01)
ridge.fit(X_train, y_train) 

C:\Users\RADHIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=1.46077e-28): result may not be accurate.
  overwrite_a=True).T


Ridge(alpha=0.01)

In [20]:
from sklearn.metrics import r2_score
pred_train_rr= ridge.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train_rr)))
print(r2_score(y_train, pred_train_rr))

pred_test_rr= ridge.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred_test_rr))) 
print(r2_score(y_test, pred_test_rr))

13.52838327896824
0.924572702493158
7.54378767247254
0.6666588378381321


In [21]:
# Calculate the absolute errors
errors_ridge = abs(pred_test_rr - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 6.56 degrees.


In [22]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_ridge / pred_test_rr)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Accuracy: 93.61 %.


In [23]:
import pickle
pickle.dump(rfjpnmodel,open('rf_chn_model.pkl','wb'))