In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
canada=pd.read_csv('D:/Technocolabs Final work files/k=5_MergedData/Canada.csv')

In [3]:
canada.head()

Year       PPP  Exchange           GDP  vector_1  vector_2  vector_3  \
0  1981  1.134429  1.198903  3.060000e+11  0.100003  0.100004  0.100066   
1  1982  1.162983  1.233735  3.140000e+11  0.200000  0.200000  0.200000   
2  1983  1.183882  1.232412  3.410000e+11  0.092599  0.552755  0.166161   
3  1984  1.183059  1.295066  3.550000e+11  0.100043  0.599702  0.100172   
4  1985  1.185080  1.365507  3.650000e+11  0.082920  0.350074  0.399832   

   vector_4  vector_5  
0  0.100020  0.599906  
1  0.200000  0.200000  
2  0.095321  0.093163  
3  0.100015  0.100069  
4  0.083997  0.083177

In [4]:
X=canada.drop('Exchange',axis=1)
X

Year       PPP           GDP  vector_1  vector_2  vector_3  vector_4  \
0   1981  1.134429  3.060000e+11  0.100003  0.100004  0.100066  0.100020   
1   1982  1.162983  3.140000e+11  0.200000  0.200000  0.200000  0.200000   
2   1983  1.183882  3.410000e+11  0.092599  0.552755  0.166161  0.095321   
3   1984  1.183059  3.550000e+11  0.100043  0.599702  0.100172  0.100015   
4   1985  1.185080  3.650000e+11  0.082920  0.350074  0.399832  0.083997   
5   1986  1.197798  3.770000e+11  0.100043  0.599706  0.100168  0.100014   
6   1987  1.224895  4.310000e+11  0.200000  0.200000  0.200000  0.200000   
7   1988  1.236884  5.070000e+11  0.100043  0.599704  0.100169  0.100014   
8   1989  1.246188  5.650000e+11  0.267549  0.082896  0.482542  0.083702   
9   1990  1.241965  5.940000e+11  0.200000  0.200000  0.200000  0.200000   
10  1991  1.237998  6.100000e+11  0.200000  0.200000  0.200000  0.200000   
11  1992  1.228098  5.920000e+11  0.100003  0.100004  0.100066  0.100020   
12  1993  1.215102  5.770000e+11  0.077464  0.073236  0.230987  0.077500   
13  1994  1.207010  5.780000e+11  0.599077  0.100005  0.100662  0.100023   
14  1995  1.208841  6.040000e+11  0.088975  0.085419  0.085452  0.087372   
15  1996  1.207821  6.290000e+11  0.151969  0.153923  0.074708  0.074724   
16  1997  1.200974  6.530000e+11  0.666820  0.082881  0.083114  0.083779   
17  1998  1.185448  6.320000e+11  0.200000  0.200000  0.200000  0.200000   
18  1999  1.190810  6.760000e+11  0.100004  0.100023  0.598393  0.101306   
19  2000  1.227563  7.420000e+11  0.079377  0.207023  0.076489  0.077989   
20  2001  1.221139  7.360000e+11  0.100003  0.100004  0.100066  0.100020   
21  2002  1.229333  7.580000e+11  0.093425  0.080196  0.102873  0.082508   
22  2003  1.226338  8.920000e+11  0.082981  0.076759  0.098497  0.079952   
23  2004  1.233195  1.020000e+12  0.082920  0.358420  0.083097  0.082907   
24  2005  1.213644  1.170000e+12  0.100004  0.100023  0.598410  0.101290   
25  2006  1.205778  1.320000e+12  0.200000  0.200000  0.200000  0.200000   
26  2007  1.212706  1.460000e+12  0.100043  0.599705  0.100169  0.100014   
27  2008  1.234390  1.550000e+12  0.599080  0.100005  0.100659  0.100023   
28  2009  1.201369  1.370000e+12  0.666814  0.082881  0.083114  0.083784   
29  2010  1.221371  1.610000e+12  0.666819  0.082881  0.083114  0.083779   
30  2011  1.239904  1.790000e+12  0.100004  0.100023  0.598416  0.101283   
31  2012  1.244607  1.830000e+12  0.100004  0.100023  0.598395  0.101305   
32  2013  1.224000  1.850000e+12  0.599083  0.100005  0.100655  0.100023   
33  2014  1.230358  1.800000e+12  0.200000  0.200000  0.200000  0.200000   
34  2015  1.248042  1.560000e+12  0.596414  0.100008  0.100008  0.102422   
35  2016  1.207045  1.530000e+12  0.200000  0.200000  0.200000  0.200000   
36  2017  1.212304  1.650000e+12  0.100043  0.599705  0.100169  0.100014   
37  2018  1.198165  1.720000e+12  0.506295  0.272260  0.073604  0.074063   

    vector_5  
0   0.599906  
1   0.200000  
2   0.093163  
3   0.100069  
4   0.083177  
5   0.100069  
6   0.200000  
7   0.100069  
8   0.083311  
9   0.200000  
10  0.200000  
11  0.599907  
12  0.540812  
13  0.100233  
14  0.652782  
15  0.544675  
16  0.083406  
17  0.200000  
18  0.100275  
19  0.559122  
20  0.599907  
21  0.640998  
22  0.661811  
23  0.392656  
24  0.100275  
25  0.200000  
26  0.100069  
27  0.100233  
28  0.083406  
29  0.083406  
30  0.100274  
31  0.100275  
32  0.100233  
33  0.200000  
34  0.101148  
35  0.200000  
36  0.100069  
37  0.073779

In [6]:
y=canada['Exchange']
y

0     1.198903
1     1.233735
2     1.232412
3     1.295066
4     1.365507
5     1.389471
6     1.325983
7     1.230701
8     1.183972
9     1.166774
10    1.145726
11    1.208723
12    1.290088
13    1.365673
14    1.372445
15    1.363522
16    1.384598
17    1.483505
18    1.485705
19    1.485394
20    1.548840
21    1.570343
22    1.401015
23    1.301282
24    1.211405
25    1.134345
26    1.074046
27    1.067087
28    1.141535
29    1.030113
30    0.989258
31    0.999365
32    1.030137
33    1.104747
34    1.278786
35    1.325615
36    1.297936
37    1.295818
Name: Exchange, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression
lcanmodel=LinearRegression()
lcanmodel.fit(X_train,y_train)

LinearRegression()

In [9]:
y_pred=lcanmodel.predict(X_test)
y_pred

array([1.4155614 , 1.07188879, 1.39879873, 1.40883664, 1.30004343,
       1.47285359, 1.15449348, 1.24640535])

In [10]:
from sklearn.metrics import mean_squared_error
lcanmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(lcanmodel_rmse)

0.06608095832311463


In [11]:
from sklearn import metrics
print(metrics.mean_absolute_error(y_test,y_pred))

0.058034107355071834


In [12]:
# Calculate the absolute errors
errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.06 degrees.


In [13]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 95.23 %.


In [14]:
from sklearn.ensemble import RandomForestRegressor
rfcanmodel=RandomForestRegressor(n_estimators = 1000, random_state = 42)
rfcanmodel.fit(X_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [16]:
y_pred_rf=rfcanmodel.predict(X_test)
y_pred_rf

array([1.45552413, 1.1699968 , 1.29914595, 1.37514565, 1.32881912,
       1.39465907, 1.2481661 , 1.21736162])

In [18]:
from sklearn.metrics import mean_squared_error
rfcanmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred_rf))
print(rfcanmodel_rmse)

0.11380932089877044


In [19]:
rfcanmodel.feature_importances_

array([0.17041113, 0.16462053, 0.38165662, 0.07371431, 0.04539802,
       0.04771787, 0.04085453, 0.07562699])

In [22]:
# Calculate the absolute errors
errors_rf = abs(y_pred_rf - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.1 degrees.


In [23]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_rf / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 91.64 %.


### Ridge

In [25]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.01)
ridge.fit(X_train, y_train) 

C:\Users\RADHIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=1.08101e-27): result may not be accurate.
  overwrite_a=True).T


Ridge(alpha=0.01)

In [26]:
from sklearn.metrics import r2_score
pred_train_rr= ridge.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train_rr)))
print(r2_score(y_train, pred_train_rr))

pred_test_rr= ridge.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred_test_rr))) 
print(r2_score(y_test, pred_test_rr))

0.04476686602451127
0.9035395583647703
0.06776311748959427
0.8416177050223401


In [27]:
# Calculate the absolute errors
errors_ridge = abs(pred_test_rr - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.1 degrees.


In [28]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_ridge / pred_test_rr)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Accuracy: 95.38 %.


In [29]:
import pickle
pickle.dump(ridge,open('ridge_chn_model.pkl','wb'))