In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
uk=pd.read_csv('D:/Technocolabs Final work files/k=5_MergedData/UK.csv')

In [3]:
uk.head()

Year       PPP  Exchange           GDP  vector_1  vector_2  vector_3  \
0  1981  0.511874  0.497641  5.410000e+11  0.100003  0.100004  0.100066   
1  1982  0.517855  0.572447  5.150000e+11  0.200000  0.200000  0.200000   
2  1983  0.523865  0.659725  4.900000e+11  0.092599  0.552755  0.166161   
3  1984  0.531057  0.751807  4.610000e+11  0.100043  0.599702  0.100172   
4  1985  0.543150  0.779246  4.890000e+11  0.082920  0.350074  0.399832   

   vector_4  vector_5  
0  0.100020  0.599906  
1  0.200000  0.200000  
2  0.095321  0.093163  
3  0.100015  0.100069  
4  0.083997  0.083177

In [5]:
X=uk.drop('Exchange',axis=1)
X

Year       PPP           GDP  vector_1  vector_2  vector_3  vector_4  \
0   1981  0.511874  5.410000e+11  0.100003  0.100004  0.100066  0.100020   
1   1982  0.517855  5.150000e+11  0.200000  0.200000  0.200000  0.200000   
2   1983  0.523865  4.900000e+11  0.092599  0.552755  0.166161  0.095321   
3   1984  0.531057  4.610000e+11  0.100043  0.599702  0.100172  0.100015   
4   1985  0.543150  4.890000e+11  0.082920  0.350074  0.399832  0.083997   
5   1986  0.555510  6.010000e+11  0.100043  0.599706  0.100168  0.100014   
6   1987  0.571600  7.450000e+11  0.200000  0.200000  0.200000  0.200000   
7   1988  0.585987  9.100000e+11  0.100043  0.599704  0.100169  0.100014   
8   1989  0.608630  9.270000e+11  0.267549  0.082896  0.482542  0.083702   
9   1990  0.632935  1.090000e+12  0.200000  0.200000  0.200000  0.200000   
10  1991  0.651530  1.140000e+12  0.200000  0.200000  0.200000  0.200000   
11  1992  0.658168  1.180000e+12  0.100003  0.100004  0.100066  0.100020   
12  1993  0.660507  1.060000e+12  0.077464  0.073236  0.230987  0.077500   
13  1994  0.655710  1.140000e+12  0.599077  0.100005  0.100662  0.100023   
14  1995  0.714632  1.340000e+12  0.088975  0.085419  0.085452  0.087372   
15  1996  0.714617  1.420000e+12  0.151969  0.153923  0.074708  0.074724   
16  1997  0.708919  1.560000e+12  0.666820  0.082881  0.083114  0.083779   
17  1998  0.720742  1.650000e+12  0.200000  0.200000  0.200000  0.200000   
18  1999  0.725819  1.680000e+12  0.100004  0.100023  0.598393  0.101306   
19  2000  0.704306  1.660000e+12  0.079377  0.207023  0.076489  0.077989   
20  2001  0.694382  1.640000e+12  0.100003  0.100004  0.100066  0.100020   
21  2002  0.689877  1.780000e+12  0.093425  0.080196  0.102873  0.082508   
22  2003  0.696596  2.050000e+12  0.082981  0.076759  0.098497  0.079952   
23  2004  0.688410  2.420000e+12  0.082920  0.358420  0.083097  0.082907   
24  2005  0.707619  2.540000e+12  0.100004  0.100023  0.598410  0.101290   
25  2006  0.697420  2.710000e+12  0.200000  0.200000  0.200000  0.200000   
26  2007  0.710100  3.100000e+12  0.100043  0.599705  0.100169  0.100014   
27  2008  0.701691  2.920000e+12  0.599080  0.100005  0.100659  0.100023   
28  2009  0.709551  2.410000e+12  0.666814  0.082881  0.083114  0.083784   
29  2010  0.701707  2.480000e+12  0.666819  0.082881  0.083114  0.083779   
30  2011  0.706052  2.660000e+12  0.100004  0.100023  0.598416  0.101283   
31  2012  0.701634  2.700000e+12  0.100004  0.100023  0.598395  0.101305   
32  2013  0.695248  2.790000e+12  0.599083  0.100005  0.100655  0.100023   
33  2014  0.698444  3.060000e+12  0.200000  0.200000  0.200000  0.200000   
34  2015  0.692551  2.930000e+12  0.596414  0.100008  0.100008  0.102422   
35  2016  0.688603  2.690000e+12  0.200000  0.200000  0.200000  0.200000   
36  2017  0.684601  2.670000e+12  0.100043  0.599705  0.100169  0.100014   
37  2018  0.683551  2.860000e+12  0.506295  0.272260  0.073604  0.074063   

    vector_5  
0   0.599906  
1   0.200000  
2   0.093163  
3   0.100069  
4   0.083177  
5   0.100069  
6   0.200000  
7   0.100069  
8   0.083311  
9   0.200000  
10  0.200000  
11  0.599907  
12  0.540812  
13  0.100233  
14  0.652782  
15  0.544675  
16  0.083406  
17  0.200000  
18  0.100275  
19  0.559122  
20  0.599907  
21  0.640998  
22  0.661811  
23  0.392656  
24  0.100275  
25  0.200000  
26  0.100069  
27  0.100233  
28  0.083406  
29  0.083406  
30  0.100274  
31  0.100275  
32  0.100233  
33  0.200000  
34  0.101148  
35  0.200000  
36  0.100069  
37  0.073779

In [6]:
y=uk['Exchange']
y

0     0.497641
1     0.572447
2     0.659725
3     0.751807
4     0.779246
5     0.682197
6     0.611927
7     0.562170
8     0.611173
9     0.563177
10    0.567015
11    0.569774
12    0.666757
13    0.653427
14    0.633668
15    0.640958
16    0.610836
17    0.603824
18    0.618057
19    0.660931
20    0.694655
21    0.667223
22    0.612473
23    0.546180
24    0.549998
25    0.543487
26    0.499772
27    0.543966
28    0.641919
29    0.647179
30    0.624141
31    0.633047
32    0.639661
33    0.607730
34    0.654545
35    0.740634
36    0.776977
37    0.749532
Name: Exchange, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression
lukmodel=LinearRegression()
lukmodel.fit(X_train,y_train)

LinearRegression()

In [9]:
y_pred=lukmodel.predict(X_test)
y_pred

array([0.60480442, 0.65955893, 0.61440834, 0.62152397, 0.59779544,
       0.66648147, 0.47776062, 0.5943485 ])

In [10]:
from sklearn.metrics import mean_squared_error
lukmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(lukmodel_rmse)

0.020655003201783876


In [11]:
from sklearn import metrics
print(metrics.mean_absolute_error(y_test,y_pred))

0.018574148430402733


In [12]:
# Calculate the absolute errors
errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.02 degrees.


In [13]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 96.88 %.


### Random Forest

In [14]:
from sklearn.ensemble import RandomForestRegressor
rfukmodel=RandomForestRegressor(n_estimators = 1000, random_state = 42)
rfukmodel.fit(X_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [15]:
y_pred_rf=rfukmodel.predict(X_test)
y_pred_rf

array([0.64189505, 0.63328886, 0.63547807, 0.62753544, 0.60660662,
       0.60759959, 0.62881773, 0.57942262])

In [16]:
from sklearn.metrics import mean_squared_error
rfukmodel_rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(rfukmodel_rmse)

0.020655003201783876


In [18]:
rfukmodel.feature_importances_

array([0.32367735, 0.0775044 , 0.18192362, 0.02485987, 0.13547739,
       0.0490027 , 0.07340868, 0.13414599])

In [19]:
# Calculate the absolute errors
errors_rf = abs(y_pred_rf - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.02 degrees.


In [20]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_rf / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 92.49 %.


### Ridge Regression

In [21]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.01)
ridge.fit(X_train, y_train) 

C:\Users\RADHIKA\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=3.82712e-28): result may not be accurate.
  overwrite_a=True).T


Ridge(alpha=0.01)

In [22]:
from sklearn.metrics import r2_score
pred_train_rr= ridge.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train_rr)))
print(r2_score(y_train, pred_train_rr))

pred_test_rr= ridge.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred_test_rr))) 
print(r2_score(y_test, pred_test_rr))

0.032184459608282694
0.7975276959550144
0.021055167288602416
0.8578864409627045


In [23]:
# Calculate the absolute errors
errors_ridge = abs(pred_test_rr - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.02 degrees.


In [24]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors_ridge / pred_test_rr)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 96.8 %.


In [25]:
import pickle
pickle.dump(ridge,open('ridge_uk_model.pkl','wb'))